"use client";
import { useState } from "react";
import { Category, CategoryId } from "../game/types";
interface Props { playerName: string; onNameChange: (name: string) => void; categories: Array<Category & { questionCount: number }>; categoryId: CategoryId; onCategoryChange: (id: CategoryId) => void; timeLimit: number; onTimeChange: (seconds: number) => void; onStart: (count: number) => void; loading?: boolean; error?: string; }
export function SetupScreen({ playerName, onNameChange, categories, categoryId, onCategoryChange, timeLimit, onTimeChange, onStart, loading, error }: Props) {
  const available = categories.find((item) => item.id === categoryId)?.questionCount ?? 0; const [count, setCount] = useState(5); const [customCount, setCustomCount] = useState(""); const [customTime, setCustomTime] = useState("");
  const selectedCount = customCount ? Number(customCount) : count; const selectedTime = customTime ? Number(customTime) : timeLimit; const validCount = Number.isInteger(selectedCount) && selectedCount >= 1 && selectedCount <= available; const validTime = Number.isInteger(selectedTime) && selectedTime >= 10 && selectedTime <= 300;
  const chooseCount = (option: number) => { setCustomCount(""); setCount(option); }; const chooseTime = (option: number) => { setCustomTime(""); onTimeChange(option); };
  return <section className="panel setup-panel"><span className="brand"><i>✦</i> nexora</span><div className="step"><span>01</span><hr /><span>02</span><hr /><span>03</span></div><p className="eyebrow">LET&apos;S SET THE STAGE</p><h2>Ready when you are<span>.</span></h2><label className="field-label">WHAT SHOULD WE CALL YOU?</label><input className="name-input" value={playerName} onChange={(event) => onNameChange(event.target.value)} placeholder="Enter your name" maxLength={30} autoFocus />
  <label className="field-label">CHOOSE YOUR ARENA</label><div className="category-grid">{categories.map((category, index) => <button key={category.id} className={`category-option ${category.color ?? ["violet", "cyan", "orange"][index % 3]} ${categoryId === category.id ? "selected" : ""}`} onClick={() => onCategoryChange(category.id)}><b>{category.icon ?? "✦"}</b><span>{category.name}</span><small>{category.description ?? `${category.questionCount} questions available`}</small><i>✓</i></button>)}</div>
  <div className="config-row"><div><label className="field-label">QUESTIONS</label><div className="pill-group">{[5, 10, 15, 20].map((option) => <button disabled={option > available} key={option} className={selectedCount === option ? "active" : ""} onClick={() => chooseCount(option)}>{option}</button>)}</div><input className="mini-input" type="number" min="1" max={available} value={customCount} placeholder="Custom" onChange={(event) => setCustomCount(event.target.value)} /></div><div><label className="field-label">TIME PER QUESTION</label><div className="pill-group">{[10, 15, 30, 45, 60].map((option) => <button key={option} className={selectedTime === option ? "active" : ""} onClick={() => chooseTime(option)}>{option}s</button>)}</div><input className="mini-input" type="number" min="10" max="300" value={customTime} placeholder="Custom seconds" onChange={(event) => setCustomTime(event.target.value)} /></div></div><p className={`availability ${error || !validCount || !validTime ? "error" : ""}`}>{loading ? "Loading quiz arenas…" : error ?? (!validCount ? `This category currently has only ${available} questions. Choose between 1 and ${available}.` : !validTime ? "Choose a timer between 10 and 300 seconds." : `${available} unique questions available in this arena.`)}</p><button disabled={loading || !!error || !playerName.trim() || !validCount || !validTime} className="primary-button start-button" onClick={() => { onTimeChange(selectedTime); onStart(selectedCount); }}>Start quiz <span>→</span></button></section>;
}
