import { Category, Question } from "@/components/game/types";

export const categories: Category[] = [
  { id: "mathematics", name: "Mathematics", description: "Numbers, patterns & logic", icon: "∑", color: "violet" },
  { id: "coding", name: "Coding", description: "Build, debug & think", icon: "</>", color: "cyan" },
  { id: "computer-science", name: "Computer Science", description: "Systems, data & the web", icon: "◈", color: "orange" },
];

// This data is deliberately plain TypeScript/JSON-shaped so it can move to an API or MongoDB later.
export const questions: Question[] = [
  { id: "math-001", category: "mathematics", question: "What is 15% of 200?", answer: "30", difficulty: "easy", explanation: "0.15 × 200 = 30." },
  { id: "math-002", category: "mathematics", question: "Solve for x: 2x + 4 = 10.", answer: "3", difficulty: "easy", explanation: "Subtract 4, then divide by 2." },
  { id: "math-003", category: "mathematics", question: "What is the next prime number after 29?", answer: "31", difficulty: "medium" },
  { id: "math-004", category: "mathematics", question: "A triangle has angles of 50° and 60°. What is its third angle in degrees?", answer: "70", acceptedAnswers: ["70°"], difficulty: "easy" },
  { id: "math-005", category: "mathematics", question: "Express 0.75 as a simplified fraction.", answer: "3/4", difficulty: "easy" },
  { id: "math-006", category: "mathematics", question: "What is the probability of rolling an even number on a fair six-sided die?", answer: "1/2", acceptedAnswers: ["0.5", "50%"], difficulty: "medium" },
  { id: "math-007", category: "mathematics", question: "What is the square root of 144?", answer: "12", difficulty: "easy" },
  { id: "math-008", category: "mathematics", question: "If a $80 item is discounted by 25%, what is the sale price?", answer: "60", acceptedAnswers: ["$60"], difficulty: "medium" },
  { id: "math-009", category: "mathematics", question: "What is the greatest common divisor of 18 and 24?", answer: "6", difficulty: "medium" },
  { id: "math-010", category: "mathematics", question: "Solve: 3² + 4² = ?", answer: "25", difficulty: "easy" },
  { id: "math-011", category: "mathematics", question: "What is the area of a rectangle with width 7 and height 5?", answer: "35", difficulty: "easy" },
  { id: "math-012", category: "mathematics", question: "A sequence starts 2, 4, 8, 16. What comes next?", answer: "32", difficulty: "easy" },
  { id: "code-001", category: "coding", question: "In JavaScript, which keyword creates a block-scoped variable that can be reassigned?", answer: "let", difficulty: "easy" },
  { id: "code-002", category: "coding", question: "What data structure follows Last In, First Out (LIFO)?", answer: "stack", difficulty: "easy" },
  { id: "code-003", category: "coding", question: "What is the time complexity of binary search?", answer: "O(log n)", acceptedAnswers: ["o(log n)", "logarithmic"], difficulty: "medium" },
  { id: "code-004", category: "coding", question: "Which HTTP method is conventionally used to create a resource?", answer: "POST", difficulty: "easy" },
  { id: "code-005", category: "coding", question: "What does JSON stand for?", answer: "JavaScript Object Notation", difficulty: "easy" },
  { id: "code-006", category: "coding", question: "In Python, which keyword defines a function?", answer: "def", difficulty: "easy" },
  { id: "code-007", category: "coding", question: "What is a function that calls itself called?", answer: "recursive", acceptedAnswers: ["recursion", "recursive function"], difficulty: "medium" },
  { id: "code-008", category: "coding", question: "Which Git command records staged changes in the repository history?", answer: "git commit", difficulty: "easy" },
  { id: "code-009", category: "coding", question: "What TypeScript feature lets you describe the shape of an object without generating JavaScript?", answer: "interface", difficulty: "medium" },
  { id: "code-010", category: "coding", question: "What does API stand for?", answer: "Application Programming Interface", difficulty: "easy" },
  { id: "code-011", category: "coding", question: "Which loop is best suited when you know the number of iterations in advance?", answer: "for loop", acceptedAnswers: ["for"], difficulty: "easy" },
  { id: "code-012", category: "coding", question: "What keyword exits a loop immediately in many programming languages?", answer: "break", difficulty: "easy" },
  { id: "cs-001", category: "computer-science", question: "Which operating system component manages hardware resources?", answer: "kernel", difficulty: "medium" },
  { id: "cs-002", category: "computer-science", question: "What protocol translates domain names into IP addresses?", answer: "DNS", acceptedAnswers: ["Domain Name System"], difficulty: "easy" },
  { id: "cs-003", category: "computer-science", question: "Which database property means a transaction is all-or-nothing?", answer: "atomicity", difficulty: "hard" },
  { id: "cs-004", category: "computer-science", question: "What does CPU stand for?", answer: "Central Processing Unit", difficulty: "easy" },
  { id: "cs-005", category: "computer-science", question: "What is the smallest unit of data in computing?", answer: "bit", difficulty: "easy" },
  { id: "cs-006", category: "computer-science", question: "What network device forwards packets between networks?", answer: "router", difficulty: "medium" },
  { id: "cs-007", category: "computer-science", question: "Which data structure uses key-value pairs?", answer: "hash table", acceptedAnswers: ["hashmap", "map", "dictionary"], difficulty: "medium" },
  { id: "cs-008", category: "computer-science", question: "What does SQL stand for?", answer: "Structured Query Language", difficulty: "easy" },
  { id: "cs-009", category: "computer-science", question: "What is a process waiting forever for a resource held by another process called?", answer: "deadlock", difficulty: "hard" },
  { id: "cs-010", category: "computer-science", question: "Which cloud model provides virtual machines, storage, and networking?", answer: "IaaS", acceptedAnswers: ["Infrastructure as a Service"], difficulty: "medium" },
  { id: "cs-011", category: "computer-science", question: "What is the primary purpose of a firewall?", answer: "filter network traffic", acceptedAnswers: ["network traffic filtering", "to filter network traffic"], difficulty: "medium" },
  { id: "cs-012", category: "computer-science", question: "What does RAM stand for?", answer: "Random Access Memory", difficulty: "easy" },
];
