"use client";
import { CSSProperties, FormEvent, useEffect, useState } from "react";
import { AnswerRecord, Category, Question } from "./types";
interface Props { playerName: string; category: Category; question: Question; questionNumber: number; total: number; score: number; remaining: number; timeLimit: number; feedback?: AnswerRecord; onSubmit: (answer: string) => void; onNext: () => void; onQuit: () => void; }
export function QuizScreen({ playerName, category, question, questionNumber, total, score, remaining, timeLimit, feedback, onSubmit, onNext, onQuit }: Props) {
  const [answer, setAnswer] = useState(""); useEffect(() => setAnswer(""), [question.id]); useEffect(() => { if (!feedback) return; const id = window.setTimeout(onNext, 2200); return () => window.clearTimeout(id); }, [feedback, onNext]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (!feedback) onSubmit(answer); }; const percent = Math.max(0, (remaining / timeLimit) * 100); const urgent = remaining <= Math.ceil(timeLimit * .25); const explanation = feedback?.explanation ?? question.explanation;
  return <section className="quiz-page"><header className="game-header"><span className="brand"><i>✦</i> nexora</span><div className="player-chip"><span className="avatar">{playerName.slice(0, 1).toUpperCase()}</span><span><small>PLAYER</small>{playerName}</span></div><div className="score-chip"><small>SCORE</small><b>{score}</b><span>PTS</span></div><button className="quiz-quit" onClick={onQuit}>Quit</button></header><div className="quiz-content"><div className="quiz-topline"><span className={`subject-badge ${category.color}`}>{category.icon} {category.name}</span><span className="question-count">QUESTION <b>{String(questionNumber).padStart(2, "0")}</b> / {String(total).padStart(2, "0")}</span></div><div className="progress-track"><i style={{ width: `${((questionNumber - 1) / total) * 100}%` }} /></div><div className="timer-wrap"><div className={`timer-ring ${urgent ? "urgent" : ""}`} style={{ "--progress": `${percent * 3.6}deg` } as CSSProperties}><b>{remaining}</b><small>SEC</small></div><span>{urgent ? "Time is running out!" : "Stay focused"}</span></div><article className="question-card"><p className="question-label">{question.difficulty} challenge</p><h1>{question.question}</h1><form onSubmit={submit}><label className="field-label">YOUR ANSWER</label><div className="answer-row"><input disabled={!!feedback} value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Type your answer here..." autoFocus /><button disabled={!!feedback || !answer.trim()} className="submit-button" type="submit">Submit <span>↵</span></button></div></form>{feedback && <div className={`feedback ${feedback.status}`}><b>{feedback.status === "correct" ? "+10  Correct!" : feedback.status === "unanswered" ? "Time's up" : "Not quite"}</b><span>{feedback.status === "correct" ? explanation ?? "Beautiful work — keep the momentum going." : <>The answer was <strong>{feedback.correctAnswer}</strong>{explanation ? ` — ${explanation}` : ""}</>}</span></div>}</article><div className="quiz-footer"><span>Progress <b>{Math.round((questionNumber / total) * 100)}%</b></span><span>{total - questionNumber} questions remaining</span></div></div></section>;
}
