"use client";
import { useEffect, useMemo, useState } from "react";
import { advanceQuiz, answerQuiz, completeQuiz, CompleteResponse, getCategories, quitQuiz, startQuiz } from "@/lib/api";
import { AnswerRecord, Category, CategoryId, Question } from "./types";
import { SetupScreen } from "../setup/SetupScreen";
import { QuizScreen } from "./QuizScreen";
import { ResultsScreen } from "../results/ResultsScreen";
type Screen = "landing" | "setup" | "quiz" | "results";
const colorFor = (id: string) => id === "mathematics" ? "violet" : id === "coding" ? "cyan" : "orange";
export function QuizGame() {
  const [screen, setScreen] = useState<Screen>("landing"), [playerName, setPlayerName] = useState(""), [categoryId, setCategoryId] = useState<CategoryId>("mathematics"), [timeLimit, setTimeLimit] = useState(30), [categories, setCategories] = useState<Array<Category & { questionCount: number }>>([]), [activeQuestions, setActiveQuestions] = useState<Question[]>([]), [index, setIndex] = useState(0), [records, setRecords] = useState<AnswerRecord[]>([]), [remaining, setRemaining] = useState(30), [deadline, setDeadline] = useState(0), [startedAt, setStartedAt] = useState(0), [sessionId, setSessionId] = useState(""), [apiError, setApiError] = useState(""), [loading, setLoading] = useState(false), [result, setResult] = useState<CompleteResponse>();
  useEffect(() => { getCategories().then((items) => { const decorated = items.map((item) => ({ ...item, color: colorFor(item.id) })); setCategories(decorated); if (decorated.length && !decorated.some((item) => item.id === categoryId)) setCategoryId(decorated[0].id); }).catch((error: Error) => setApiError(error.message)); }, []);
  const category = categories.find((item) => item.id === categoryId) ?? { id: categoryId, name: "Quiz", icon: "✦", color: "violet" }; const current = activeQuestions[index]; const score = records.reduce((total, record) => total + (record.status === "correct" ? 10 : 0), 0);
  useEffect(() => { if (screen !== "quiz" || !deadline || !current || records[index] || loading) return; const syncRemaining = () => setRemaining(Math.max(0, Math.ceil((deadline - Date.now()) / 1000))); syncRemaining(); const timer = window.setInterval(syncRemaining, 250); window.addEventListener("visibilitychange", syncRemaining); return () => { window.clearInterval(timer); window.removeEventListener("visibilitychange", syncRemaining); }; }, [screen, deadline, current, records, index, loading]);
  useEffect(() => { if (screen === "quiz" && remaining <= 0 && current && !records[index] && !loading) void submitAnswer(""); }, [screen, remaining, current, records, index, loading]);
  async function begin(count: number) { setLoading(true); setApiError(""); try { const session = await startQuiz({ playerName, categoryId, questionCount: count, timePerQuestionSeconds: timeLimit, difficulty: "mixed" }); setSessionId(session.sessionId); setActiveQuestions(session.questions); setRecords([]); setResult(undefined); setIndex(0); setStartedAt(Date.now()); setDeadline(Date.parse(session.startedAt) + session.timePerQuestionSeconds * 1000); setScreen("quiz"); } catch (error) { setApiError(error instanceof Error ? error.message : "Could not start the quiz."); } finally { setLoading(false); } }
  async function submitAnswer(answer: string) { if (!current || records[index] || loading) return; setLoading(true); try { const response = await answerQuiz(sessionId, current.id, answer); setRecords((items) => [...items, { question: current, answer, status: response.status, elapsedSeconds: timeLimit - remaining, correctAnswer: response.correctAnswer, explanation: response.explanation }]); } catch (error) { setApiError(error instanceof Error ? error.message : "Could not submit that answer."); } finally { setLoading(false); } }
  async function advance() { setLoading(true); try { if (index + 1 < activeQuestions.length) { const next = await advanceQuiz(sessionId); setIndex((value) => value + 1); setDeadline(Date.parse(next.questionStartedAt) + timeLimit * 1000); return; } setResult(await completeQuiz(sessionId)); setScreen("results"); } catch (error) { setApiError(error instanceof Error ? error.message : "Could not advance the quiz."); } finally { setLoading(false); } }
  async function quit() { setLoading(true); try { setResult(await quitQuiz(sessionId)); setScreen("results"); } catch (error) { setApiError(error instanceof Error ? error.message : "Could not quit the quiz."); } finally { setLoading(false); } }
  const elapsed = startedAt ? Math.max(1, Math.round((Date.now() - startedAt) / 1000)) : 0;
  const view = useMemo(() => { if (screen === "landing") return <Landing onPlay={() => setScreen("setup")} />; if (screen === "setup") return <SetupScreen playerName={playerName} onNameChange={setPlayerName} categories={categories} categoryId={categoryId} onCategoryChange={setCategoryId} timeLimit={timeLimit} onTimeChange={setTimeLimit} onStart={begin} loading={loading} error={apiError} />; if (screen === "quiz" && current) return <QuizScreen playerName={playerName} category={category} question={current} questionNumber={index + 1} total={activeQuestions.length} score={score} remaining={remaining} timeLimit={timeLimit} feedback={records[index]} onSubmit={submitAnswer} onNext={advance} onQuit={quit} />; return <ResultsScreen playerName={playerName} category={category} records={records} totalTime={result?.totalTimeSeconds ?? elapsed} result={result} onPlayAgain={() => { setApiError(""); setScreen("setup"); }} onHome={() => setScreen("landing")} />; }, [screen, playerName, categories, categoryId, timeLimit, activeQuestions, index, records, remaining, score, elapsed, result, apiError, loading]);
  return <main className="app-shell">{apiError && screen !== "setup" && <p className="availability error">{apiError}</p>}{view}</main>;
}
function Landing({ onPlay }: { onPlay: () => void }) { return <section className="landing"><nav><span className="brand"><i>✦</i> nexora</span><a className="nav-tag" href="/social">SOCIAL ARENA</a></nav><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="landing-copy"><p className="eyebrow">LEVEL UP YOUR MIND</p><h1>Think fast.<br /><em>Learn more.</em><br />Become sharper.</h1><p className="hero-text">A high-energy knowledge game built for curious minds. Pick a subject, beat the clock, and find your next personal best.</p><div className="landing-actions"><button className="primary-button" onClick={onPlay}>Play now <span>→</span></button><a className="social-button" href="/social"><i>◉</i><span>Play with friends<small>LIVE 1V1 & TEAMS</small></span><b>→</b></a></div><p className="mini-proof"><b>3</b> subjects <span>•</span> server-scored rounds</p></div><div className="floating-card card-math"><b>∑</b><span>Mathematics</span><small>Quiz arena</small></div><div className="floating-card card-code"><b>&lt;/&gt;</b><span>Coding</span><small>Quiz arena</small></div><div className="floating-card card-cs"><b>◈</b><span>Computer Science</span><small>Quiz arena</small></div></section>; }
