"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { io, Socket } from "socket.io-client";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
type Person = { id: string; name: string }; type Room = { id: string; name: string; mode: "duel" | "team"; members: Array<{ playerId: string; name: string; team?: string }>; messages: Message[] }; type Message = { id: string; name: string; playerId: string; text: string; createdAt: string };
async function call<T>(path: string, init?: RequestInit): Promise<T> { const r = await fetch(`${api}/social${path}`, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error(body.error?.message ?? "Something went wrong."); return body; }
export default function SocialPage() {
  const [player, setPlayer] = useState<Person | null>(null), [name, setName] = useState(""), [rooms, setRooms] = useState<Room[]>([]), [room, setRoom] = useState<Room | null>(null), [mode, setMode] = useState<"duel" | "team">("duel"), [roomName, setRoomName] = useState("Lightning lobby"), [message, setMessage] = useState(""), [notice, setNotice] = useState(""), [online, setOnline] = useState(0), [friendId, setFriendId] = useState(""), [friends, setFriends] = useState<Array<{ id: string; status: string; direction: string; player: Person }>>([]);
  const socket = useRef<Socket>();
  const loadRooms = () => call<{ data: Room[] }>("/rooms").then(({ data }) => setRooms(data)).catch((e: Error) => setNotice(e.message));
  useEffect(() => { loadRooms(); const saved = localStorage.getItem("nexora-social-player"); if (saved) { const p = JSON.parse(saved) as Person; setPlayer(p); setName(p.name); } }, []);
  useEffect(() => { if (!player || !room) return; const endpoint = api.replace(/\/api$/, ""); const current = io(endpoint); socket.current = current; current.emit("room:join", { roomId: room.id, playerId: player.id }); current.on("room:presence", ({ online: count }) => setOnline(count)); current.on("chat:message", (entry: Message) => setRoom((value) => value ? { ...value, messages: [...value.messages, entry] } : value)); current.on("room:error", setNotice); return () => { current.close(); }; }, [player, room?.id]);
  useEffect(() => { if (player) call<{ data: Array<{ id: string; status: string; direction: string; player: Person }> }>(`/friends?playerId=${encodeURIComponent(player.id)}`).then(({ data }) => setFriends(data)).catch(() => undefined); }, [player]);
  async function identify(event: FormEvent) { event.preventDefault(); try { const saved = localStorage.getItem("nexora-social-player"); const body = await call<{ player: Person }>("/identity", { method: "POST", body: JSON.stringify({ id: saved ? (JSON.parse(saved) as Person).id : undefined, name }) }); setPlayer(body.player); localStorage.setItem("nexora-social-player", JSON.stringify(body.player)); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not create your player."); } }
  async function createRoom(event: FormEvent) { event.preventDefault(); if (!player) return; try { const data = await call<{ room: Room }>("/rooms", { method: "POST", body: JSON.stringify({ host: { playerId: player.id, name: player.name }, name: roomName, mode }) }); setRoom(data.room); loadRooms(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not create lobby."); } }
  async function join(id: string) { if (!player) return; try { const data = await call<{ room: Room }>(`/rooms/${id}/join`, { method: "POST", body: JSON.stringify({ playerId: player.id, name: player.name }) }); setRoom(data.room); loadRooms(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not join lobby."); } }
  function send(event: FormEvent) { event.preventDefault(); if (!message.trim() || !room || !player) return; socket.current?.emit("chat:send", { roomId: room.id, playerId: player.id, text: message }); setMessage(""); }
  async function addFriend(event: FormEvent) { event.preventDefault(); if (!player || !friendId.trim()) return; try { await call("/friends/request", { method: "POST", body: JSON.stringify({ from: { playerId: player.id, name: player.name }, to: { playerId: friendId.trim() } }) }); setFriendId(""); const data = await call<{ data: Array<{ id: string; status: string; direction: string; player: Person }> }>(`/friends?playerId=${encodeURIComponent(player.id)}`); setFriends(data.data); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not send friend request."); } }
  if (!player) return <main className="social-page"><section className="social-hero"><a className="brand" href="/"><i>✦</i> nexora</a><p className="eyebrow">SOCIAL ARENA</p><h1>Bring your <em>brain squad.</em></h1><p>Choose a name to make friends, enter live lobbies, and chat while you challenge each other.</p><form onSubmit={identify}><input className="name-input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Your player name" maxLength={30} required /><button className="primary-button">Enter social <span>→</span></button></form></section></main>;
  if (room) return <main className="social-page"><section className="lobby-shell"><header><button className="back-button" onClick={() => { setRoom(null); loadRooms(); }}>← Lobbies</button><span className="brand"><i>✦</i> nexora</span><span className="live-dot">{online} LIVE</span></header><div className="lobby-grid"><section className="room-stage"><p className="eyebrow">{room.mode === "duel" ? "1V1 BRAIN DUEL" : "TEAM BATTLE"}</p><h1>{room.name}</h1><div className="member-grid">{room.members.map((member, index) => <div className={`member-card ${member.team ?? (index ? "cyan" : "violet")}`} key={member.playerId}><b>{member.name.slice(0, 1).toUpperCase()}</b><span>{member.name}</span><small>{member.playerId === player.id ? "YOU" : member.team ? `${member.team.toUpperCase()} TEAM` : "CHALLENGER"}</small></div>)}{Array.from({ length: Math.max(0, (room.mode === "duel" ? 2 : 4) - room.members.length) }).map((_, i) => <div className="member-card empty" key={i}>+<small>Waiting for player</small></div>)}</div><p className="stage-note">Live quiz rounds are the next social milestone. This lobby is ready for your friends and team chat.</p></section><aside className="chat-panel"><div><b>ROOM CHAT</b><span>{online} online</span></div><ol>{room.messages.map((entry) => <li key={entry.id} className={entry.playerId === player.id ? "mine" : ""}><b>{entry.name}</b><span>{entry.text}</span></li>)}</ol><form onSubmit={send}><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Send hype…" maxLength={500} /><button>↑</button></form></aside></div></section>{notice && <p className="social-notice">{notice}</p>}</main>;
  return <main className="social-page"><section className="social-dashboard"><header><a className="brand" href="/"><i>✦</i> nexora</a><span className="player-chip"><span className="avatar">{player.name[0]}</span>{player.name}</span></header><div className="social-title"><p className="eyebrow">SOCIAL ARENA</p><h1>Pick your <em>challenge.</em></h1></div><div className="social-grid"><form className="create-room" onSubmit={createRoom}><p className="eyebrow">CREATE A LOBBY</p><div className="mode-picker"><button type="button" className={mode === "duel" ? "active" : ""} onClick={() => setMode("duel")}>⚡ 1v1 Duel</button><button type="button" className={mode === "team" ? "active" : ""} onClick={() => setMode("team")}>◈ Team battle</button></div><input className="name-input" value={roomName} onChange={(e) => setRoomName(e.target.value)} maxLength={50} required /><button className="primary-button">Open lobby <span>→</span></button></form><section className="lobby-list"><div><p className="eyebrow">OPEN LOBBIES</p><button className="refresh-button" onClick={loadRooms}>↻ Refresh</button></div>{rooms.length ? rooms.map((item) => <article key={item.id}><span className={`room-mark ${item.mode}`}>{item.mode === "duel" ? "⚡" : "◈"}</span><div><b>{item.name}</b><small>{item.mode === "duel" ? "1v1 duel" : "team battle"} · {item.members.length} joined</small></div><button onClick={() => join(item.id)}>Join</button></article>) : <p className="empty-lobbies">No open lobbies yet. Start the first one.</p>}</section></div><section className="friends-panel"><div><p className="eyebrow">FRIENDS</p><span>Share your ID: <code>{player.id}</code></span></div><form onSubmit={addFriend}><input value={friendId} onChange={(e) => setFriendId(e.target.value)} placeholder="Friend's player ID" /><button>Add friend</button></form>{friends.map((friend) => <p key={friend.id}><b>{friend.player.name}</b><span>{friend.status} · {friend.direction}</span></p>)}</section></section>{notice && <p className="social-notice">{notice}</p>}</main>;
}
